Changed UI to gov style
dfe-analytical-services/education-to-employment-dashboard pull request #4
Opened 2022-04-25 08:21 UTC by liviahull

## Pull request overview

Give a general description of why a change is being made, include issue number(s) being fixed if relevant

## Pull request checklist

Please check if your PR fulfils the following:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

## What is the current behaviour?

The UI relies on shinydashboard package, has the navigation between pages through the tabs on the side bar, above the selection boxes for different categories (Region, Industry Sector and so on). Layouts are based on boxes where tables are charts are placed. 

![image](https://user-images.githubusercontent.com/30684529/165049362-6d58064a-64dd-4734-9695-39a7cf73ef27.png)

## What is the new behaviour?

The UI has changed to line up with the LEO dashboard  to be published May 2022 and govstyle (css file is in the www/ folder, and the footer is from the shinyGovstyle package).

<img width="1111" alt="qualpathways" src="https://user-images.githubusercontent.com/30684529/165047661-79b693e6-d135-4576-8a89-94593a933df1.png">

## Anything else

In addition to this, the collapsible tree on page 2 has got a legend above the chart.

2022-04-25 09:28 UTC, Jkhamis commented
Thanks Livia - this looks great. Couple of minor comments:

- In the Industry Sector Overview. Can you add some text below the KPI boxes to describe the tabs? The text should be: "Select the sub-sector and level tab for a breakdown of employee numbers and median earnings by highest level of education and detailed industry sector. Select the subject and qualification tab for more information about the highest qualifications employees hold.
- Again in the industry sector overview tab - there is a bit of space between the sector and level charts and the bottom of the pages. If this is still there with the added text then could you increase the height of the charts a little to fill it?  
- In the qualification pathways section - can you add a "how to read this chart" section under the title? I think we need to add a  short explanation there.

All my other comments are about completing the text - so that can wait. 

Thanks!
Jay

2022-04-25 10:27 UTC, Jkhamis approved these changes

2022-04-25 11:16 UTC, cjrace requested changes
Looks good - nice work on getting it all working with the new styling!

Few thoughts from looking around:

- I'd suggest removing the custom formatting from the tabs so that they're consistent with other dashboards, currently it feels like they stick out a bit too much.
- The reset button on the subject and qualification tab seems a bit lost / out of place. It should probably sit within the blue sidebar, though even then it seems like users might miss it if it's at the bottom of the page?
- The font in the drop downs seems to be different to standard and looks like it's aligned strangely?
This branch:
![image](https://user-images.githubusercontent.com/52536248/165078119-61146236-713a-4b85-9eef-6a4c05c775b0.png)
LEO dashboard (as an example of what I was expecting)
![image](https://user-images.githubusercontent.com/52536248/165078311-b32c394d-016b-40aa-82bc-d25047a555cd.png)
- Link from the homepage to qualification pathways doesn't seem to be working? (the other link above for industry sector overview does work)

2022-04-25 11:16 UTC, cjrace commented on R/accessibility_statement.R
> +    a(href = "mailto:he.leo@education.gov.uk", "he.leo@education.gov.uk", .noWS = c("after")),
Should the email address be updated?

2022-04-25 11:16 UTC, cjrace commented on R/support_links.R
> +      href = "https://forms.office.com/Pages/ResponsePage.aspx?id=yXfS-grGoU2187O4s0qC-c6JT6ONG3lJtlg-5hU4A6xURUpQME1OUVZIMEFMUUdNMEVONkhEN0g1VSQlQCN0PWcu",
This needs updating to be a form for this specific dashboard, can create a form using microsoft forms with similar questions to the SCAP form - https://forms.office.com/Pages/ResponsePage.aspx?id=yXfS-grGoU2187O4s0qC-fim2cxpeIFFus-loZuDRkhUN0ZPMlhCSDgzQjlVTjNVTFpXRTdWMlo0MC4u

2022-04-25 11:16 UTC, cjrace commented on R/support_links.R
> +    a(href = "mailto:he.leo@education.gov.uk", "he.leo@education.gov.uk", .noWS = c("after")),
Does this need updating?

2022-04-25 11:16 UTC, cjrace commented on R/support_links.R
> +    a(href = "https://github.com/dfe-analytical-services/leo-graduate-industry-dashboard", "GitHub repository", .noWS = c("after")),
Needs updating to this repository

2022-04-25 11:59 UTC, liviahull commented on R/accessibility_statement.R
> +    a(href = "mailto:he.leo@education.gov.uk", "he.leo@education.gov.uk", .noWS = c("after")),
yes but we don't have one yet

2022-04-25 12:02 UTC, rmbielby commented
Don't think I've got much extra beyond Cam's comments. Like I said in the previous PR, I think the legend circles could be bigger. We could also add the black ring around each. So something like:
```
  svg_html_legend <- paste('<svg width="450" height="20">',
                           '<circle cx="10" cy="10" r="8" style="fill: rgb(29, 112, 184);"></circle>',
                           '<circle cx="90" cy="10" r="8" style="fill: rgb(0, 48, 120);"></circle>',
                           '<circle cx="170" cy="10" r="8" style="fill: rgb(145, 43, 136);"></circle>',
                           '<circle cx="260" cy="10" r="8" style="fill: #4c2c92";></circle>',
                           '<circle cx="340" cy="10" r="8" style="fill: #28a197";></circle>',
                           '<circle cx="10" cy="10" r="8" style="fill: none; stroke: black; stroke-width: 2;"></circle>',
                           '<circle cx="90" cy="10" r="8" style="fill: none; stroke: black; stroke-width: 2;"></circle>',
                           '<circle cx="170" cy="10" r="8" style="fill: none; stroke: black; stroke-width: 2;"></circle>',
                           '<circle cx="260" cy="10" r="8" style="fill: none; stroke: black; stroke-width: 2;"></circle>',
                           '<circle cx="340" cy="10" r="8" style="fill: none; stroke: black; stroke-width: 2;"></circle>',
                           '<text x="25" y="12" alignment-baseline="middle" style="font-size: 15px;">Level 2</text>',
                            '<text x="105" y="12" alignment-baseline="middle" style="font-size: 15px;">Level 3</text>',
                            '<text x="185" y="12" alignment-baseline="middle" style="font-size: 15px;">Level 4/5</text>',
                            '<text x="275" y="12" alignment-baseline="middle" style="font-size: 15px;">Level 6</text>',
                            '<text x="355" y="12" alignment-baseline="middle" style="font-size: 15px;">Level 7+</text>')


```

2022-04-25 12:03 UTC, liviahull commented on R/support_links.R
> +    a(href = "mailto:he.leo@education.gov.uk", "he.leo@education.gov.uk", .noWS = c("after")),
Yes it does but we don't have one yet.

2022-04-25 12:18 UTC, liviahull commented on R/support_links.R
> +    a(href = "https://github.com/dfe-analytical-services/leo-graduate-industry-dashboard", "GitHub repository", .noWS = c("after")),
ok

2022-04-25 15:11 UTC, liviahull commented
@cjrace and @rmbielby I have addressed all these. In addition I added a column for level to the table. Data will show a level for each qualification regardless of "All levels" selection in the filter.

2022-04-26 07:41 UTC, cjrace approved these changes
Thanks Livia - happy to approve now

2022-04-26 07:44 UTC, merged